init-project-v2
E24U/ms-auth pull request #1
Opened 2022-09-09 11:25 UTC by Vasilenko773

Создал сервис авторизации. Перенес юзеров на jdbc, немного модернизировал логику

2022-09-09 11:27 UTC, Vasilenko773 commented
![image](https://user-images.githubusercontent.com/80044763/189339895-3aea038d-219a-4fbf-bc0f-71e6981aeced.png)

2022-09-09 11:51 UTC, AMakutsevi4 requested changes

2022-09-09 11:51 UTC, AMakutsevi4 commented on src/main/java/e24u/auth/data/user/User.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
Для удобства предлагаю методы отсортировать(constructor, getter, setter, equals, toString)

2022-09-09 11:51 UTC, AMakutsevi4 commented on src/main/java/e24u/auth/data/user/UserService.java
> +    private final UserDbRepository userDbRepository;
Предлагаю использовать record.

2022-09-09 11:51 UTC, AMakutsevi4 commented on db/users.sql
> +    login    varchar(124),
а если пользователь уже существует, где-то есть проверка на уникальность ?

2022-09-09 11:51 UTC, AMakutsevi4 commented on src/main/resources/application.properties
> +jdbc.driver=org.postgresql.Driver
плохая привычка хранить пароли в общем доступе.

2022-09-10 16:15 UTC, AMakutsevi4 approved these changes

2022-09-10 19:04 UTC, MerkurevSergei requested changes

2022-09-10 19:04 UTC, MerkurevSergei commented on .idea/.gitignore
> +# Default ignored files
почему gitignore в каталоге idea?

2022-09-16 17:31 UTC, MerkurevSergei approved these changes

2022-09-16 17:31 UTC, MerkurevSergei commented on src/main/java/e24u/auth/MsAuthApplication.java
> +//@ComponentScan(basePackages = "e24u")
А зачем коммент оставил?

2022-09-16 17:31 UTC, MerkurevSergei commented on src/main/java/e24u/auth/security/config/WebSecurity.java
> +//import lombok.AllArgsConstructor;
Ой сколько комментов, давай не будем хранить это в проекте, пока они не нужны

2022-09-16 17:32 UTC, merged