Feature/adding roles
E24U/ms-auth pull request #2
Opened 2022-09-16 09:40 UTC by Vasilenko773

Добавил Роли, crud операции, установил связь

2022-09-16 17:45 UTC, MerkurevSergei requested changes

2022-09-16 17:45 UTC, MerkurevSergei commented on .idea/.gitignore
> +# Default ignored files
Перенести gitignore в корень проекта, в этом каталоге хранить свои настройки idea

2022-09-16 17:45 UTC, MerkurevSergei commented on db/roles.sql
> +insert into roles(id, name) VALUES ('11111111-d171-4df0-8636-448d6cf2ddf8', 'администратор'),
зачем руками вводить uuid? спроси у Александра, там есть нативная функция у postgres, которая его генерирует, и не требует плагинов

2022-09-16 17:45 UTC, MerkurevSergei commented on db/users_roles.sql
> +    id      uuid primary key,
Здесь вроде id не нужен, если ы не собираемся пару user-role использовать как отдельную сущность

2022-09-16 17:45 UTC, MerkurevSergei commented on pom.xml
> +<!--        <dependency>-->
Ну можно оставить, скорее всего ты хочешь их включить, но лучше не делать из кода комменты

2022-09-16 17:45 UTC, MerkurevSergei commented on src/main/java/e24u/auth/MsAuthApplication.java
> +//@ComponentScan(basePackages = "e24u")
Зачем этот коммент тут?

2022-09-16 17:45 UTC, MerkurevSergei commented on src/main/java/e24u/auth/data/user/UserController.java
> +    @PostMapping("/user/create")
по rest post и так по умолчанию предполагает создание сущности, читал ссылочки, смотрел api, как другие делают?

2022-09-16 17:45 UTC, MerkurevSergei commented on src/main/java/e24u/auth/data/user/UserController.java
> +    @DeleteMapping("/user/drop/{uuid}")
Лучше без drop, метод delete и так ясно все говорит

2022-09-16 17:45 UTC, MerkurevSergei commented on src/main/java/e24u/auth/security/config/WebSecurity.java
> +//import lombok.AllArgsConstructor;
Зачем все эти комменты здесь), давай уберем, раз не используем

2022-09-16 17:45 UTC, MerkurevSergei commented on src/test/java/e24u/auth/MsAuthApplicationTests.java
> +class MsAuthApplicationTests {
А тесты проходят без включенного postgres?

2022-09-19 06:56 UTC, Vasilenko773 commented on src/main/java/e24u/auth/MsAuthApplication.java
> +//@ComponentScan(basePackages = "e24u")
готово

2022-09-19 07:01 UTC, Vasilenko773 commented on db/roles.sql
> +insert into roles(id, name) VALUES ('11111111-d171-4df0-8636-448d6cf2ddf8', 'администратор'),
Не согласен. Роли мы создаем самостоятельно(пока что). Не вижу проблемы чтобы присвоить им определенный uuid

2022-09-19 07:11 UTC, Vasilenko773 commented on src/main/java/e24u/auth/data/user/UserController.java
> +    @PostMapping("/user/create")
поправил на user/new и post/new
все делают по разному. было бы здорово если бы поделился опытом как надо делать)

2022-09-19 10:18 UTC, Vasilenko773 commented on db/users_roles.sql
> +    id      uuid primary key,
исправил

2022-09-19 10:18 UTC, Vasilenko773 commented on .idea/.gitignore
> +# Default ignored files
готово

2022-09-19 15:30 UTC, MerkurevSergei requested changes

2022-09-19 15:30 UTC, MerkurevSergei commented on db/roles.sql
> +insert into roles(id, name) VALUES ('11111111-d171-4df0-8636-448d6cf2ddf8', 'администратор'),
Не, там не Hibernate, у него в миграциях можно глянуть.
Проблема 1 - потенциальная уязвимость. Любой может посмотреть в git id роли и возможно как-то её использовать
Проблема 2 - ручной ввод, потом будет лень и ещё куда-то скопируем и так пойдут одинаковые uuid
На данном этапе это не такие уж критичные проблемы, но почему бы сразу тебе не научиться новой функции)))

2022-09-19 15:30 UTC, MerkurevSergei commented on src/main/java/e24u/auth/data/user/UserController.java
> +    @PostMapping("/user/new")
Зачем new?) Почему нельзя сделать просто Post /user? Почитай ссылки, я как-то кидал же вам, посмотри как обычно делают API крутые дядьки

2022-09-20 07:10 UTC, Vasilenko773 commented on db/roles.sql
> +insert into roles(id, name) VALUES ('11111111-d171-4df0-8636-448d6cf2ddf8', 'администратор'),
Поправил в рамках ветки feature/swagger

2022-09-20 07:17 UTC, Vasilenko773 commented on src/test/java/e24u/auth/MsAuthApplicationTests.java
> +class MsAuthApplicationTests {
если postgres отключить то не проходят)

2022-09-20 07:17 UTC, Vasilenko773 commented on src/main/java/e24u/auth/data/user/UserController.java
> +    @DeleteMapping("/user/drop/{uuid}")
готово

2022-09-20 07:17 UTC, Vasilenko773 commented on src/main/java/e24u/auth/data/user/UserController.java
> +    @PostMapping("/user/new")
готово

2022-09-20 20:19 UTC, MerkurevSergei approved these changes

2022-09-20 20:20 UTC, merged